### PR TITLE
AXI-AP support

### PR DESCRIPTION
**Pull request by pderouen**
- Adds AXI-AP support
- Adds a debug feature
- Docs update pending

### CODE REVIEW

**Comment by priyavadan** [comment]
@pderouen looks good to me. Does it need a spec update or is the diff based examples regression enough ?

**Comment by pderouen** [comment]
Yeah, I probably should add tests for the alternate behavior to make sure it doesn't get broken later. Looks like I should add Github Actions as well to run them.

**Comment by pderouen** [comment]
@priyavadan that's everything I had planned for this PR, plus some added tests for the new behaviors. Click approve when you're happy with it please sir.

**Review by priyavadan — APPROVED** [review]
Thank you for the updates @pderouen , appreciate it!

**Pull request merged**
