### PR TITLE
ARM Debug Plugin v1

### PR DESCRIPTION
**Pull request by ginty**
I recently had to use this plugin and found that it didn't work out of the box. Upon looking at the internals I found that it did not really use modern idiomatic Origen conventions, like using reg.read!/write!. This generally made it harder to reason about, and more so because it also supports older APIs which are already deprecated.

With ARM becoming more and more prevalent I think that this will be one of the most commonly used drivers, so I think we should invest the time to make it a real showcase plugin.
Subsequently I propose we do a major re-write, basing it entirely on the ARM Debug Interface v5 spec, ultimately with the goal of supporting it completely.

I am opening this PR now to give us an area to discuss this overhaul, it is still far from ready to go.

Here is the proposed API:

``` ruby
# For low-level manual operation, this should be done by reading/writing internal registers
# directly, this mostly works already
arm_debug.sw_dp.idcode.read!(0x2BA01477)
arm_debug.sw_dp.ctrl_stat.write!(0x5000_0000) # Power-up
arm_debug.sw_dp.ctrl_stat.read!(0xF0000000)   # Verify
arm_debug.ahb_ap.idr.read!(0x24770011)
```

Integration of the module as a sub-block and then providing a high-level read/write_register method should be pretty much as it is right now.

What's currently broken:
- Tests
- JTAG-based DP
- Automatic address increment, all mem_ap read/write operations currently force an address write

Note that if you want to try this right now, you also need the latest SWD plugin from the api_cleanup branch.

### CODE REVIEW

**Comment by ginty** [comment]
@rlaj, @chrisnappi, @coreyeng, please review.
I have a legacy NXP device which I am using to verify the SWD-based operation against. I will need to work closely with one of you to verify it against a legacy FSL device with JTAG-based operation.

**Comment by welguisz** [comment]
@ginty Agreed that the ARM Debug needs  to be updated.  The  only suggestion that I have going forward is to  make small commits to follow things along better.  For example, one commit should be "Wrote tests to test functionality A".  Next commit would be "Wrote method to cover functionality A and got tests to pass."  Trying to see everything in 1 commit is hard.  Plus having Test-Driven Development for Origen would be nice to have.

**Comment by chrisnappi** [comment]
Corey,

I think we need to use SCG and S32K or MAXXX to validate this – those are the only parts using JTAG and CATI.

Do you have VT for one of those working?

Chris

**Comment by ginty** [comment]
@welguisz I can't promise to make my commit history better, but I'll try. On the TDD I do normally try and do that, but I think that comes down to personal workflow choice. I think we do all agree that we want to have test coverage though, but how you get there is up to the individual.
I don't really want to de-rail this thread on that, but feel free to open a discussion thread on disqus if you want to discuss further.

**Comment by ginty** [comment]
Hi All,

OK I would say this update is initially done, the internals are much cleaner and simpler overall now and I think this is a good base to add any additional features you may want.

I think this change also adds auto address incrementing for the first time as the old implementation had a logic bug which meant it never actually kicked in. It now seems to be working well and passes my simulations.

My simulation covers a SWD DP case, but we need to see someone try it out on a JTAG DP. I have added the code for it though, but it is untested. I would say there is a good chance that the write side might just work, but I'm not sure about the read - not sure if it requires a buffered read like the SWD does.

This update does not support a JTAG AP, though I have added a placeholder for the code, however the initial implementation didn't either. Contributions to this would be most welcome from whoever has a use case for it.

Here is a summary of the current API:

Model instantiation is similar to before, however the class name is now DAP, though Driver is an alias and will still work.
The difference is that the key to define the APs is now 'mem_aps' instead of 'aps'. This is to allow the plugin to in future support 'jtag_aps' as well.

``` ruby
 sub_block :arm_debug, class_name: 'OrigenARMDebug::DAP',
                       mem_aps:    { ahb_ap: 0x00000000, apb_ap: 0x01000000 },
                       latency:    2
```

The old low level API has been totally removed, it now works completely from conventional Origen register transactions.

``` ruby
arm_debug.sw_dp.idcode.read!(0x2BA01477)
arm_debug.sw_dp.ctrlstat.write!(0x5000_0000) # Power-up
arm_debug.sw_dp.ctrlstat.read!(0xF0000000)   # Verify
arm_debug.ahb_ap.idr.read!(0x24770011)
arm_debug.sw_dp.select.write!(0) # Select AHB-AP, bank 0       
# Set the SIZE field of CSW to 0x2 (32-bit transfers) + AddrInc=1
arm_debug.ahb_ap.csw.write!(0x23000052)
```

The high-level register API hook up is similar to before, with one key difference - the top-level now no longer defaults to an AP selection. This means that you have to fully identify the AP you want to use when passing a register request onto ARM debug for fulfillment.
This lends itself much better to more complex cases with multiple APs and where it would be the top-level controller's responsibility to farm out requests to the correct AP.

``` ruby
def write_register(reg, options = {})
  arm_debug.ahb_ap.write_register(reg, options)
end

def read_register(reg, options = {})
  arm_debug.ahb_ap.read_register(reg, options)
end
```

So I think this does everything that I need it to for now. I probably would like to see some helpers be added for the pre-amble and to provide canned startups for some common implementations, but I have no immediate plans to add that (don't really have the experience to know what they are).

Review and further contribution is welcome...

**Comment by ginty** [comment]
Easiest way to review this by the way is probably just to look at the source code, the diff here doesn't add anything for a big change like this:

https://github.com/Origen-SDK/origen_arm_debug/tree/v1/lib/origen_arm_debug

**Comment by chrisnappi** [comment]
Hello,

VT for S32K should be working. I know I got 48 Mhz trim working then Brian took everything to the tester. Everything else should work though since it works on the tester.

I’m not sure what MAXXX is so… no. I don’t have VT for that working.

Thanks,

Corey

From: Chris Nappi
Sent: Friday, October 07, 2016 8:57 AM
To: Origen-SDK/origen_arm_debug reply@reply.github.com; Origen-SDK/origen_arm_debug origen_arm_debug@noreply.github.com; Corey Engelken corey.engelken@nxp.com
Cc: chrisnappi chris.nappi@freescale.com; Mention mention@noreply.github.com
Subject: RE: [Origen-SDK/origen_arm_debug] ARM Debug Plugin v1 (#6)

Corey,

I think we need to use SCG and S32K or MAXXX to validate this – those are the only parts using JTAG and CATI.

Do you have VT for one of those working?

Chris

**Comment by chrisnappi** [comment]
MAXXX= MA512 or MA256 ☺

Can you update to Stephen’s latest ARM driver and try a CATI pattern on a JTAG-based part?  Is S32K JTAG or SWD?

Chris

From: Corey Engelken
Sent: Monday, October 10, 2016 9:26 AM
To: Chris Nappi chris.nappi@nxp.com; Origen-SDK/origen_arm_debug reply@reply.github.com; Origen-SDK/origen_arm_debug origen_arm_debug@noreply.github.com
Cc: chrisnappi chris.nappi@freescale.com; Mention mention@noreply.github.com
Subject: RE: [Origen-SDK/origen_arm_debug] ARM Debug Plugin v1 (#6)

Hello,

VT for S32K should be working. I know I got 48 Mhz trim working then Brian took everything to the tester. Everything else should work though since it works on the tester.

I’m not sure what MAXXX is so… no. I don’t have VT for that working.

Thanks,

Corey

From: Chris Nappi
Sent: Friday, October 07, 2016 8:57 AM
To: Origen-SDK/origen_arm_debug reply@reply.github.com; Origen-SDK/origen_arm_debug <origen_arm_debug@noreply.github.com<mailto:origen_arm_debug@noreply.github.com>>; Corey Engelken <corey.engelken@nxp.com<mailto:corey.engelken@nxp.com>>
Cc: chrisnappi <chris.nappi@freescale.com<mailto:chris.nappi@freescale.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Origen-SDK/origen_arm_debug] ARM Debug Plugin v1 (#6)

Corey,

I think we need to use SCG and S32K or MAXXX to validate this – those are the only parts using JTAG and CATI.

Do you have VT for one of those working?

Chris

**Comment by rlaj** [comment]
Picking this back up again.  But JTAG side is currently not working (failing sims) in my latest project.  In debug...

**Comment by rlaj** [comment]
Made some further updates:
  -Added MDM-AP support.  These AP only have local AP registers associated with them and no resources so write_register and read_register are straightforward.  Only basic AP register definition included, will be up to arm_debug.owner to define (add) any specifics
 -Updated JTAG-DP, mainly focused on second DR shift for read case to actually shift out the expected data.  This also required an update to origen_jtag to allow for non-zero shift in data during a read_dr method.
 -Updated MEM-AP to set CSW(size) if necessary.  Only supports 32-bit wide accesses right now
 -More granularity for latency.   Added wait variables to AP classes so each can be specified at the top-level if necessary, and split out into what type of AP access (register or resource) is being performed.

Did not push the approved examples yet, so build will fail, but wanted to get some eyes on these updates before proceeding.  Also planning to circle back and scrub origen_jtag and clean up the hack mentioned above.

UPDATE: After a little more debug, turns out the origen_jtag hack mentioned above is not required.  However, correct operation does require that the jtag.read_dr ALWAYS shift in all 0s.  I still think it's a limitation of the JTAG driver to not be able to specific datain and dataout on the same shift.

**Comment by ginty** [comment]
Hi @rlaj, what's an MDM-AP? I don't see that term referenced anywhere in the ARM debug interface spec and I think we should not be introducing non-std terms or concepts here.

I see the spec only talk about:

MEM-AP
JTAG-AP
SWD-DP
JTAG-DP

**Comment by rlaj** [comment]
Those are the only AP specifically defined by ARM.  However, the ARM Debug Interface spec also allows for additional, designer-specified/implemented APs.  MDM-AP is a common one used by one of the leading ARM-based microcontroller manufacturers in the world.

I considered keeping it out and having it defined at the top-level, but that puts a heavy burden on the end user.  Maybe a company-specific shim is more suitable?

**Comment by ginty** [comment]
By "one of the leading ARM-based microcontroller manufacturers in the world" do you mean NXP?
If so, vs. say some 3rd party vendor who's solution could be used within another company, then I think this is not the place for it if it is a company-specific thing.
I agree that it shouldn't be done at app-level, but a company specific plugin, arm_debug_nxp, which adds the necessary extensions seems more appropriate.
Of course you can add whatever generic hooks you like here to make writing that extension easier.

**Comment by chrisnappi** [comment]
I think it is okay to leave it in here for now - but later maybe some mechanism to be able to describe custom APs?

**Comment by ginty** [comment]
Well, this is a PR for ARM debug v1, a major clean up and potential API change, so I don't think this really is the place for temporary hacks to be put in under time pressure if that's what you mean.
You can branch or add an update to v0.x if you want to add a quick solution, but this PR should take it back out again.

**Comment by ginty** [comment]
Btw, the reason I am really against non-std stuff going in here, is because this plugin did not work when I went to use it on another device family. Then when I looked at the ARM debug spec and the initial version of this plugin it was very hard to work out what was going on exactly because it had been written to a more company-specific version of ARM debug.
This PR and V1 release is therefore specifically an attempt to put us back on a more generic footing.

**Comment by chrisnappi** [comment]
I guess I don't see this as non-standard - it is an example of a supported-by-spec extension.  So it needs to support such extensions cleanly - maybe it already does?

**Comment by ginty** [comment]
I don't think its the responsibility of this plugin to provide a driver for company-specific variants.
If someone is approaching this plugin to understand it so that they can make an update to it, where is the intended function of MDM-AP documented? Everything else is in the ARM spec.

It sounds like MDM-AP is a custom memory access point. Until @rlaj's update, only this API is supported to instantiate an ARM driver:

~~~ruby
sub_block :arm_debug, class_name: 'OrigenARMDebug::DAP',
                      mem_aps:    { ahb_ap: 0x00000000, apb_ap: 0x01000000 }
~~~

For sure I can see the need now to add support for something like this instead:

~~~ruby
sub_block :arm_debug, class_name: 'OrigenARMDebug::DAP',
                      mem_aps: { ahb_ap: 0x00000000,   # Instantiates an OrigenARMDebug::MemAP
                                 apb_ap: { address: 0x01000000, class_name: "NXPArmDebug::MdmAP" }
                               }
~~~

However, where NXPArmDebug::MdmAP is actually defined is somewhere else.

**Comment by chrisnappi** [comment]
Yes, this is what I meant, but I don't think including MDMAP as an example is a bad thing.

**Comment by rlaj** [comment]
I agree with this, I'll rework it.  

Maybe just a generic AccessPort class that can be the base for MemAP and JTAGAP and also be user-friendly for a company-specific extension?

**Comment by ginty** [comment]
Maybe I'm unfamiliar with the spec with regards to extensions, but I would have expected OrigenARMDebug::MemAP or one of the other main types to be the super class of a company-specific extension.
Is that not the case?

**Comment by rlaj** [comment]
Not exactly.  The MemAP is specific to accessing Memory resources through the port (the JTAG-AP access JTAG devices through the port).  It's not really a requirement for a user-defined implementation to have any resources at all.  For example, the NXP MDM-AP only has AP-level registers (no resources), and therefore has completely different AP-register definitions than a MemAP.

**Comment by ginty** [comment]
OK, fair enough, thanks.

**Comment by rlaj** [comment]
Made the updates as discussed.

This push is passing sims with a new, local company-specific layer plugin that implements the MDM-AP.

**Comment by ginty** [comment]
OK, looks good.

You'll need to review/approve this SWD PR before we can release this:
https://github.com/Origen-SDK/origen_swd/pull/2

**Comment by rlaj** [comment]
@ginty @chrisnappi With the latest overlay updates to SWD and some additional overlay-specific updates here, I think we may be ready to release ARM Debug v1.  Please have a look.

**Comment by ginty** [comment]
Your update looks good to me @rlaj.

Btw, if you haven't already make sure you read the RFC on digital source/capture and chime in if you have any concerns or suggestions: https://github.com/Origen-SDK/rfcs/pull/2

The changes being discussed there should take the load off drivers when it comes to overlay implementation and it means that things like having to pass :no_subr should go away in favour of setting a tester configuration attribute to select the style of overlay you want to generate.

**Pull request merged**
