### PR TITLE
Ack

### PR DESCRIPTION
**Pull request by pderouen**
* Add optional check for the acknowledge signature when shifting out an AP read (original behavior of masking the wait/acknowledge bits is retained as the default)
* Documentation update

Github Actions were a pain to get working (AGAIN!). I can't remember the last time it wasn't broken and requiring rounds of trial and error to get it working again. This time it was the Windows checks (AGAIN!) not being able to complete bundle install successfully. With version 2.3.23 of bundler installation of kramdown failed. So, I fixed the bundler version to 2.3.22.

The addition of the acknowledge check is so that you can have confidence that the operation completed successfully, and the bits being shifted out correspond to the register read that was requested.

### CODE REVIEW

**Comment by pderouen** [comment]
@chrisnappi @coreyeng @ginty @info-rchitect @priyavadan @redxeth @rlaj 
Any objections to this update or changes you'd like to see? ...I'm not sure who else is using this plugin.

**Comment by pderouen** [comment]
Any thoughts on this PR?

**Review by coreyeng — APPROVED** [review]
Looks okay to me. Default behavior looks like no acknowledgement so shouldn't change anything we currently have.

**Comment by pderouen** [comment]
> Looks okay to me. Default behavior looks like no acknowledgement so shouldn't change anything we currently have.

Thanks. Yes, that is correct the response bits are by default masked which was the original behavior. So, the update is backwards compatible with existing applications.

**Pull request merged**
