### PR TITLE
Cleanup of the register flags when reading or capturing a register.

### PR DESCRIPTION
**Pull request by coreyeng**
Hello,

This is a very, very, (VERY!) overdue PR to cleanup the register flags resulting from a <code>read</code> or <code>capture</code> operation.

Just as a refresher, this is Origen-SDK/origen#280 in which doing back-to-back read-then-capture operations would cause the register to get stuck storing unless the flags were manually cleared.

That is, this code:

~~~ruby
dut.mem(dut.ram.end_addr).write!(0xABCD_DCBA)
dut.mem(dut.ram.end_addr).read!(0xABCD_DCBA)
dut.mem(dut.ram.end_addr).store!

dut.mem(dut.ram.start_addr).write!(0x5555_AAAA)
dut.mem(dut.ram.start_addr).read!(0x5555_AAAA)
dut.mem(dut.ram.start_addr).store!

dut.mem(dut.ram.start_addr).write!(0xAAAA_AAAA)
dut.mem(dut.ram.start_addr).read!(0xAAAA_AAAA)
dut.mem(dut.ram.start_addr).store!
~~~

Would yield 2 reads and 4 captures (missing one of the reads, adding a test hole), instead of 3 reads and 3 captures:

image

With this fix, the behavior is as expected.

image

### CODE REVIEW

**Comment by ginty** [comment]
What if `reg_or_val` is a val(ue) ?

**Comment by coreyeng** [comment]
Isn't using ARM debug with non-register models not supported anymore? I can add a <code>respond_to?</code> condition to it, but I didn't worry about it here.

**Review by pderouen — APPROVED** [review]
Thanks for adding this.

**Comment by ginty** [comment]
> Isn't using ARM debug with non-register models not supported anymore? 

Not sure, is it?

Regardless, from my pov the unwritten(!) convention is that the Origen register interface has the signature:

~~~ruby
def write_regster(reg_or_val, options = {})
end

def read_register(reg_or_val, options = {})
end
~~~

Which means that you can call it with:

~~~ruby
dut.read_register(<reg_obj>)

# Override address
dut.read_register(<reg_obj>, address: 0x1000_0100)

# Use a data value instead of a reg
dut.read_register(0x1111_2222, address: 0x1000_0100)
~~~

Sure, `<reg_obj>.read!` is the recommended way which would resolve to the first method call internally, but apps should be able to rely on the latter if they want to do some explicit operations.

Maybe that's not used much in practice, but most drivers do support that.

**Review by ginty — APPROVED** [review]
Thanks for the update.

**Review by rlaj — APPROVED** [review]
LGTM

**Pull request merged**
